# Use root/example as user/password credentials
version: '3.9'

services:

  thumbor:
    image: ghcr.io/minimalcompact/thumbor:7.6.0
    environment:
      LOADER: thumbor.loaders.file_loader
      FILE_LOADER_ROOT_PATH: /data
    volumes:
      - ./images:/data
      - ./config/thumbor.conf:/etc/thumbor/thumbor.conf
    ports:
      - "8888:80"
    networks:
      - app

  nginx-proxy:
    image: ghcr.io/minimalcompact/thumbor-nginx-proxy-cache
    environment:
      # setting the DEFAULT_HOST to the same as the VIRTUAL_HOST above.
      # Makes sure it works irrespective of the host name
      # Normally this won't be necessary, but it helps for testing.
      - DEFAULT_HOST=localhost
      # optional: control cache memory size (default 500m), cache size (default 10g) and inactive (default 300m)
      #           see https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_path
      - PROXY_CACHE_SIZE=10g
      - PROXY_CACHE_MEMORY_SIZE=500m
      - PROXY_CACHE_INACTIVE=300m
    volumes:
      # this is essential for nginx-proxy to detect docker containers, scaling etc
      # see https://github.com/nginx-proxy/nginx-proxy
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # mapping cache folder, to persist it independently of the container
      - ./cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongodb}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DB:-mongodb}
      BLOG_USER: ${BLOG_USER:-blogusr}
      BLOG_PASSWORD: ${BLOG_PASSWORD:-blogpw}
    volumes:
      - ./mongo-data:/data/db:Z
      - ./mongo-log:/var/log/mongodb:Z
      - ./docker/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./docker/seeding:/docker/seeding
    networks:
      - app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT:-mongodb}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-mongodb}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT:-mongodb}:${MONGO_ROOT_PASSWORD:-mongodb}@mongo:27017/
    networks:
      - app

volumes:
  cache:
    driver: local
networks:
  app:
    driver: bridge